run:
  timeout: 10m
  # default uses Go version from the go.mod file, fallback on the env var
  # `GOVERSION`, fallback on 1.17: https://golangci-lint.run/usage/configuration/#run-configuration
  go: "1.23"

linters:
  enable:
    - bodyclose
    - depguard
    - forbidigo
    - gocritic
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - makezero
    - misspell
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - testifylint
    - typecheck
    - unused
    - whitespace
  disable-all: true

linters-settings:
  gocritic:
    disabled-checks:
      - "ifElseChain"
      - "assignOp"
      - "appendAssign"
      - "singleCaseSwitch"
      - "exitAfterDefer" # FIXME
  govet:
    enable:
      - nilness
      - unusedwrite
  depguard:
    rules:
      main:
        deny:
          - pkg: "io/ioutil"
            desc: The io/ioutil package has been deprecated.
  forbidigo:
    forbid:
      - '^fmt\.Errorf(# use errors\.Errorf instead)?$'
  gosec:
    excludes:
      - G204  # Audit use of command execution
      - G402  # TLS MinVersion too low
      - G115  # integer overflow conversion
    config:
      G306: "0644"
  testifylint:
    disable:
      # disable rules that reduce the test condition
      - "empty"
      - "bool-compare"
      - "len"
      - "negative-positive"

issues:
  exclude-files:
    - ".*\\.pb\\.go$"
  exclude-rules:
    - linters:
        - revive
      text: "stutters"
    - linters:
        - revive
      text: "empty-block"
    - linters:
        - revive
      text: "superfluous-else"
    - linters:
        - revive
      text: "unused-parameter"
    - linters:
        - revive
      text: "redefines-builtin-id"
    - linters:
        - revive
      text: "if-return"

  # show all
  max-issues-per-linter: 0
  max-same-issues: 0
