site_name: ddns-route53
site_description: Dynamic DNS for Amazon Route 53 on a time-based schedule
site_author: CrazyMax
site_url: https://crazymax.dev/ddns-route53/
edit_uri: edit/master/docs/
docs_dir: docs

repo_name: crazy-max/ddns-route53
repo_url: https://github.com/crazy-max/ddns-route53

extra:
  seo:
    google: Kscpetr5E2zNDM0pqz-0xhtPZ77oY2oAS6Lid6yEUUM
    bing: D188E0BEC1AB6E7C1E0194BFC35D0033
    #alexa:
    #yandex:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/crazy-max/ddns-route53
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/crazyws
  plausible:
    server: plausible.re4per.com
    domain: crazymax.dev/ddns-route53

theme:
  name: material
  custom_dir: docs/_overrides
  language: en
  features:
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo.png
  favicon: assets/favicon.ico
  include_search_page: false
  search_index_only: true

extra_css:
  - assets/stylesheets/extra.css

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - markdown_include.include:
      base_path: docs
  - meta
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

plugins:
  - exclude:
      glob:
        - "_overrides/*"
  - git-revision-date-localized:
      type: iso_datetime
      enable_creation_date: true
  - macros
  - search:
      lang:
        - en

nav:
  - Home: index.md
  - Installation:
    - With Docker: install/docker.md
    - From binary: install/binary.md
    - Linux service: install/linux-service.md
    - UniFi (VyOS) device: install/unifi.md
    - UniFi OS device: install/unifi-os.md
  - Usage:
    - Prerequisites: usage/prerequisites.md
    - Command line: usage/cli.md
    - Basic example: usage/basic-example.md
  - Configuration:
    - Overview: config/index.md
    - .credentials: config/credentials.md
    - .route53: config/route53.md
  - FAQ: faq.md
  - Changelog: changelog.md
  - Migration:
    - ddns-route53 v1 to v2: migration/v1-to-v2.md
  - Reporting an issue: reporting-issue.md
  - Contributing: contributing.md
  - Donate: donate.md
