name: docs

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
  pull_request:

env:
  DESTDIR: ./bin
  DOCKER_BUILD_SUMMARY: false

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # required to push to gh-pages
    steps:
      -
        name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0
      -
        name: Build docs
        uses: docker/bake-action@018cb6412ab401ebaa809aa5f85966b74628600f # v7.4.0
        with:
          source: .
          provenance: false
          targets: docs
      -
        name: Check GitHub Pages status
        uses: crazy-max/ghaction-github-status@f0ef9e1cf727f9f76f8485f8c525fa03afc4ec02 # v5.0.0
        with:
          pages_threshold: major_outage
      -
        name: Deploy
        if: github.event_name != 'pull_request'
        uses: crazy-max/ghaction-github-pages@1d6ee9b181a81033a16bd707a1401afa978daab4 # v5.0.0
        with:
          target_branch: gh-pages
          build_dir: ${{ env.DESTDIR }}/site
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
